// <auto-generated />
namespace StudentIdentity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedFixedDataForeignKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedFixedDataForeignKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "202001122151385_SeedFixedDataForeignKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
